try

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,34 +1,62 @@
 # Travis (https://travis-ci.org) configuration file
 
 language: python
-sudo: required
-services:
-  - docker
-python:
-  - "2.7"
-  - "3.4"
+matrix:
+    include:
+        #- os: linux
+        #  python: 2.7
+        #  sudo: required
+
+#          env: TRAVIS_PYTHON_VERSION=2.7
+#          script:
+#            # listing everything in howto folder recursively
+#            - ls -alR ./howto/
+#            # setting flag: don't proceed if one of commands fails.
+#            - set -e
+#            # creating folder for tests (travis doesn't allow this).
+#            - mkdir -p ./.cache/rep
+#            # testing all but notebooks
+#            - nosetests -v --detailed-errors --nocapture ./tests/test_*
+#            # testing only notebooks
+#            - nosetests -v --detailed-errors --nocapture --stop ./tests/z_test_*
+#            # if on master and tests passed successfully, trigger rebuilding of docker image.
+#            - if [[ "$TRAVIS_BRANCH" = "master" && "${TRAVIS_PYTHON_VERSION:0:1}" = "2" ]] ; then make push-latest ; fi
+#            # reseting flag
+#            - set +e
+#        - os: linux
+#          env: TRAVIS_PYTHON_VERSION=3.5
+        - os: osx
+          language: generic
+#          env: TRAVIS_PYTHON_VERSION=2.7
+#        - os: osx
+#          env: TRAVIS_PYTHON_VERSION=3.5
+
 before_install:
-  - source ci/install_repbase.sh
+  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
+      brew update;
+      brew install python;
+      brew install homebrew/science/root;
+      virtualenv venv -p python2.7;
+      source venv/bin/activate
+      source $(brew --prefix root)/libexec/thisroot.sh;
+      which root;
+      pip install pip -U;
+      pip install -r requirements.txt;
+      pip install rootpy root_numpy;
+    else
+      source ci/install_repbase.sh;
+      conda list;
+    fi
   # printing DEBUG information
   - which python
-  - conda list
   - echo $LD_LIBRARY_PATH
 install:
   - pip install .
 script:
-  # listing everything in howto folder recursively
-  - ls -alR ./howto/
-  # setting flag: don't proceed if one of commands fails.
-  - set -e
+  # creating folder for tests (travis doesn't allow this).
   - mkdir -p ./.cache/rep
   # testing all but notebooks
   - nosetests -v --detailed-errors --nocapture ./tests/test_*
-  # testing only notebooks
-  - nosetests -v --detailed-errors --nocapture --stop ./tests/z_test_*
-  # if on master and tests passed successfully, trigger rebuilding of docker image.
-  - if [[ "$TRAVIS_BRANCH" = "master" && "${TRAVIS_PYTHON_VERSION:0:1}" = "2" ]] ; then make push-latest ; fi
-  # reseting flag
-  - set +e
 notifications:
   email: true
   webhooks:
